# Generated by Django 3.2.4 on 2021-06-20 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=32)),
                ('url', models.URLField()),
                ('description', models.TextField(blank=True)),
                ('last_verified', models.DateTimeField(blank=True, null=True)),
                ('tags', models.ManyToManyField(to='wiki.Tag')),
            ],
        ),
    ]
