version: "3"
services:

  mindwiki-dev:
    build: ../..
    environment:
      DEBUG: "True"
      DATA_DIR: "/var/lib/mindwiki/"
    ports:
      - "8080:1312"
    volumes:
      - ${PROJECT_DIR}:/usr/src/mindwiki
      - mindwiki-dev-data:/var/lib/mindwiki

volumes:
  mindwiki-dev-data:
